### ISSUE TITLE
Trailing slash in niet perse nodig bij sommige elementen

### ISSUE THREAD

**Issue by DamianR2004** [Patrickkhr/opdracht-component-detail-pagina#4]
De validator vind het niet leuk als er gebruik wordt gemaakt van een / aan het einde van een of een link of meta. Het heeft geen invloed op de pagina als je deze weg haalt.

https://github.com/Patrickkhr/opdracht-component-detail-pagina/blob/9369066ee44571249b64d01f482b2a1d0eaa4592/index.html#L5

**Comment by Patrickkhr** [comment]
Ik heb het weggehaald, bedankt voor de tip.

https://github.com/Patrickkhr/opdracht-component-detail-pagina/blob/1ae53a7b0b10df6ffc643228f76629a765e3c4fe/index.html#L4
