### ISSUE TITLE
Article lacks heading

### ISSUE THREAD

**Issue by DamianR2004** [Patrickkhr/opdracht-component-detail-pagina#5]
Kijk of je nog een heading kan toevoegen aan dit article, de validator wilt dit perse zien. Mocht je geen heading in kunnen voegen zou ik misschien een section gebruiken.

https://github.com/Patrickkhr/opdracht-component-detail-pagina/blob/9369066ee44571249b64d01f482b2a1d0eaa4592/index.html#L416

**Comment by Patrickkhr** [comment]
Yes bedankt voor de tip, ik heb het probleem opgelost!

https://github.com/Patrickkhr/opdracht-component-detail-pagina/blob/1ae53a7b0b10df6ffc643228f76629a765e3c4fe/index.html#L416-L422
