### ISSUE TITLE
Heading in article

### ISSUE THREAD

**Issue by Jesse-Kramer** [Patrickkhr/opdracht-component-detail-pagina#6]
Vergeet geen heading toe te voegen aan je heading.
https://github.com/Patrickkhr/opdracht-component-detail-pagina/blob/9369066ee44571249b64d01f482b2a1d0eaa4592/index.html#L416-L421

**Comment by Patrickkhr** [comment]
Yes bedankt voor de tip, ik heb het probleem opgelost!

https://github.com/Patrickkhr/opdracht-component-detail-pagina/blob/1ae53a7b0b10df6ffc643228f76629a765e3c4fe/index.html#L416-L422
