### ISSUE TITLE
Article heeft geen heading

### ISSUE THREAD

**Issue by RobbyRisse** [Patrickkhr/opdracht-component-detail-pagina#7]
Dit artikel heeft geen heading. Overweeg om de h2-h6 elementen te gebruiken om identificerende heading toe te voegen aan alle artikelen.

dat is hier te zien:

```
<article class="card"> 
   <img src="#" alt="card"> 
   <div> 
     <p>Begeleidende tekst bij de afbeelding</p> 
   </div> 
 </article> 
```
hier een voorbeeld van hoe je het wel zou kunnen doen:

```
   <article class="card">
   <h2>Card Heading</h2>
   <img src="#" alt="card"> 
   <div> 
     <p>Begeleidende tekst bij de afbeelding</p> 
   </div> 
</article>
```

hier een bron wat dit nader verklaart: "Each article should be identified, typically by including a heading as a child of the article element." 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article

**Comment by Patrickkhr** [comment]
Yes bedankt voor de tip, ik heb het probleem opgelost!

https://github.com/Patrickkhr/opdracht-component-detail-pagina/blob/1ae53a7b0b10df6ffc643228f76629a765e3c4fe/index.html#L416-L422
